# Generated by Django 3.1.12 on 2025-01-21 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_salesorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='reserved_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
